Repository pixl8/Preside-CMS, pull requests merged in 2020-01, with the labels that each got.

#726 PRESIDECMS-1771 - fix delete empty many to many records
  system/services/presideObjects/PresideObjectService.cfc
Labels: Merged waiting release

#713 PRESIDECMS-1736 missing grant access to all logged in users toggle
  system/forms/preside-objects/asset/admin.edit.xml
  system/i18n/preside-objects/asset.properties
Labels: Received - awaiting triage and merge

#725 PRESIDECMS-1769 impersonate indication on admin toolbar
  system/coldboxModifications/RequestContextDecorator.cfc
  system/i18n/cms.properties
  system/views/general/_adminToolbar.cfm
Labels: Review feedback pending rework/response
